[package]
name = "tee-worker-pre-compute"
version = "0.5.0"
edition = "2024"

[dependencies]
aes = "0.9.3"
alloy-signer = "2.4.1"
alloy-signer-local = "2.4.1"
base64 = "0.22.1"
cbc = { version = "0.2.1", features = ["alloc"] }
env_logger = { version = "0.11.11", default-features = false, features = ["auto-color", "humantime"] }
log = "0.4.34"
multiaddr = "0.19.0"
reqwest = { version = "0.13.4", default-features = false, features = ["blocking", "json", "default-tls"] }
serde = "1.0.229"
sha256 = { version = "1.6.0", default-features = false }
sha3 = "0.10.8"
strum = "0.28.0"
strum_macros = "0.28.0"
thiserror = "2.0.20"

[dev-dependencies]
mockall = "0.15.0"
serde_json = "1.0.151"
temp-env = "0.3.6"
tempfile = "3.27.0"
testcontainers = { version = "0.28.0", default-features = false, features = ["blocking"] }
testing_logger = "0.1.1"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
wiremock = "0.6.5"
