name: Rust CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/rust-build.yml@rust-build-v2.1.0
    with:
      rust-version: '1.88.0'
      working-directory: "."
      enable-cache: true
      publish-crates-io: false

  prepare:
    name: Determine image tag
    needs: build-and-test
    runs-on: ubuntu-latest
    if: |
      github.ref_name == 'main' ||
      startsWith(github.head_ref, 'feat/') ||
      startsWith(github.head_ref, 'fix/') ||
      (github.event_name == 'workflow_dispatch' && (startsWith(github.ref_name, 'feat/') || startsWith(github.ref_name, 'fix/')))
    outputs:
      image_tag: ${{ steps.determine-tag.outputs.image_tag }}
    steps:
      - name: Determine base tag
        id: determine-tag
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ] ; then
            SHORT_SHA=$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-8)
          else
            SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
          fi

          if [ "${{ github.ref_name }}" = "main" ] ; then
            echo "Processing main branch"
            echo "image_tag=dev-${SHORT_SHA}" | tee -a $GITHUB_OUTPUT
          else
            # This covers feat/ and fix/ branches
            echo "Processing feat/fix branch ${{ github.head_ref }}"
            echo "image_tag=feature-${SHORT_SHA}" | tee -a $GITHUB_OUTPUT
          fi

  build-oci-image:
    name: Build OCI images
    needs: prepare
    strategy:
      matrix:
        package: [post-compute, pre-compute]
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/docker-build.yml@docker-build-v3.3.0
    with:
      image-name: docker-regis.iex.ec/tee-worker-${{ matrix.package }}-rust
      image-tag: ${{ needs.prepare.outputs.image_tag }}
      dockerfile: ${{ matrix.package }}/Dockerfile
      context: .
      registry: docker-regis.iex.ec
      push: true
      security-scan: true
      security-report: "sarif"
      hadolint: true
      platform: linux/amd64
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN_PULL_ONLY }}
      username: ${{ secrets.NEXUS_USERNAME }}
      password: ${{ secrets.NEXUS_PASSWORD }}
